server:
  port: 8082
spring:
  application:
    name: profile-service
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_profile}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  # Configuración del servidor WebFlux
  codec:
    max-in-memory-size: 10MB
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}
  instance:
      prefer-ip-address: true

cloudinary:
  cloud_name: ${CLOUDINARY_NAME:dep5zhuay}
  api_key: ${CLOUDINARY_API_KEY:613478824826563}
  api_secret: ${CLOUDINARY_API_SECRET:TnM60owVajuJDqAInSYvD_3u7_Y}

services:
  identity-service:
    url: ${IDENTITY_SERVICE_URL:http://IDENTITY-SERVICE}
  catalog-service:
    uri: ${CATALOG_SERVICE_URL:http://CATALOG-SERVICE}
  booking-service:
    url: ${BOOKING_SERVICE_URL:http://BOOKING-SERVICE}
