server:
  port: ${PORT:8084}

spring:
  application:
    name: booking-service
  #Configuración de R2DBC para MySQL
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_booking}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    pool:
      enabled: true
      initial-size: 5
      max-size: 10

  # Configuración del servidor WebFlux
  codec:
    max-in-memory-size: 10MB
  cloud:
    config:
      enabled: false

# Opcional: Para ver las consultas SQL en consola
logging:
  level:
    org.springframework.r2dbc: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/ # Aquí le avisa a Eureka que existe
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}
  instance:
      prefer-ip-address: true

google:
  maps:
    api-key: ${API_KEY_GOOGLE_MAPS}

services:
  profile-service:
    url: ${PROFILE_SERVICE_URL:http://PROFILE-SERVICE}
